/* AUTO-GENERATED BY hiram_c_exporter.py - ZERO-MALLOC EMBEDDED C RUNTIME */
/* MISRA-C:2012 Rule 17.2 Compliant: Static Topological Circuit Tables */
#ifndef HIRAM_CIRCUIT_DATA_H
#define HIRAM_CIRCUIT_DATA_H

/* Circuit dimensions are defined BEFORE including hiram_eval.h so that
   HiramContext.memo is sized from the authoritative generated value.
   hiram_eval.h carries no default: a translation unit that allocates a
   HiramContext without this header fails to compile rather than silently
   building a context smaller than the kernel writes into. */
#define CIRCUIT_NODE_COUNT   81
#define CIRCUIT_ROOT_ID      80
#define HAZARD_VAR_ID        5
#define CHILDREN_ARRAY_SIZE  108
#define WEIGHTS_ARRAY_SIZE   36

#include "hiram_eval.h"



/* Variable ID aliases */
#define VAR_TERRAIN_CLEAR            0
#define VAR_ALTITUDE_STABLE          1
#define VAR_DESCENT_PERMITTED        2
#define VAR_LOW_AIRSPEED             3
#define VAR_HIGH_ANGLE_OF_ATTACK     4
#define VAR_STALL_HAZARD             5
#define VAR_FREEZING_TEMP            6
#define VAR_HIGH_HUMIDITY            7
#define VAR_ICING_HAZARD             8
#define VAR_HIGH_G_LOAD              9
#define VAR_AIRFRAME_STRESS          10
#define VAR_STRUCTURAL_HAZARD        11

static const CircuitNode g_circuit_nodes[CIRCUIT_NODE_COUNT] = {
    { NODE_LITERAL, 0, 0, 0, 0, 0 },
    { NODE_LITERAL, 0, 1, 0, 0, 0 },
    { NODE_LITERAL, 1, 0, 0, 0, 0 },
    { NODE_LITERAL, 1, 1, 0, 0, 0 },
    { NODE_LITERAL, 2, 0, 0, 0, 0 },
    { NODE_LITERAL, 2, 1, 0, 0, 0 },
    { NODE_LITERAL, 3, 0, 0, 0, 0 },
    { NODE_LITERAL, 3, 1, 0, 0, 0 },
    { NODE_LITERAL, 4, 0, 0, 0, 0 },
    { NODE_LITERAL, 4, 1, 0, 0, 0 },
    { NODE_LITERAL, 5, 0, 0, 0, 0 },
    { NODE_LITERAL, 5, 1, 0, 0, 0 },
    { NODE_LITERAL, 6, 0, 0, 0, 0 },
    { NODE_LITERAL, 6, 1, 0, 0, 0 },
    { NODE_LITERAL, 7, 0, 0, 0, 0 },
    { NODE_LITERAL, 7, 1, 0, 0, 0 },
    { NODE_LITERAL, 8, 0, 0, 0, 0 },
    { NODE_LITERAL, 8, 1, 0, 0, 0 },
    { NODE_LITERAL, 9, 0, 0, 0, 0 },
    { NODE_LITERAL, 9, 1, 0, 0, 0 },
    { NODE_LITERAL, 10, 0, 0, 0, 0 },
    { NODE_LITERAL, 10, 1, 0, 0, 0 },
    { NODE_LITERAL, 11, 0, 0, 0, 0 },
    { NODE_LITERAL, 11, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 0, 0 },
    { NODE_SUM, 0, 0, 1, 2, 0 },
    { NODE_PROD, 0, 0, 2, 3, 0 },
    { NODE_PROD, 0, 0, 2, 5, 0 },
    { NODE_SUM, 0, 0, 2, 7, 1 },
    { NODE_PROD, 0, 0, 2, 9, 0 },
    { NODE_PROD, 0, 0, 2, 11, 0 },
    { NODE_SUM, 0, 0, 2, 13, 3 },
    { NODE_PROD, 0, 0, 2, 15, 0 },
    { NODE_PROD, 0, 0, 2, 17, 0 },
    { NODE_SUM, 0, 0, 2, 19, 5 },
    { NODE_PROD, 0, 0, 2, 21, 0 },
    { NODE_PROD, 0, 0, 2, 23, 0 },
    { NODE_SUM, 0, 0, 2, 25, 7 },
    { NODE_PROD, 0, 0, 2, 27, 0 },
    { NODE_SUM, 0, 0, 1, 29, 9 },
    { NODE_PROD, 0, 0, 2, 30, 0 },
    { NODE_PROD, 0, 0, 2, 32, 0 },
    { NODE_SUM, 0, 0, 2, 34, 10 },
    { NODE_PROD, 0, 0, 2, 36, 0 },
    { NODE_PROD, 0, 0, 2, 38, 0 },
    { NODE_SUM, 0, 0, 2, 40, 12 },
    { NODE_PROD, 0, 0, 2, 42, 0 },
    { NODE_PROD, 0, 0, 2, 44, 0 },
    { NODE_SUM, 0, 0, 2, 46, 14 },
    { NODE_PROD, 0, 0, 2, 48, 0 },
    { NODE_PROD, 0, 0, 2, 50, 0 },
    { NODE_SUM, 0, 0, 2, 52, 16 },
    { NODE_PROD, 0, 0, 2, 54, 0 },
    { NODE_SUM, 0, 0, 1, 56, 18 },
    { NODE_PROD, 0, 0, 2, 57, 0 },
    { NODE_PROD, 0, 0, 2, 59, 0 },
    { NODE_SUM, 0, 0, 2, 61, 19 },
    { NODE_PROD, 0, 0, 2, 63, 0 },
    { NODE_PROD, 0, 0, 2, 65, 0 },
    { NODE_SUM, 0, 0, 2, 67, 21 },
    { NODE_PROD, 0, 0, 2, 69, 0 },
    { NODE_PROD, 0, 0, 2, 71, 0 },
    { NODE_SUM, 0, 0, 2, 73, 23 },
    { NODE_PROD, 0, 0, 2, 75, 0 },
    { NODE_PROD, 0, 0, 2, 77, 0 },
    { NODE_SUM, 0, 0, 2, 79, 25 },
    { NODE_PROD, 0, 0, 2, 81, 0 },
    { NODE_SUM, 0, 0, 1, 83, 27 },
    { NODE_PROD, 0, 0, 2, 84, 0 },
    { NODE_PROD, 0, 0, 2, 86, 0 },
    { NODE_SUM, 0, 0, 2, 88, 28 },
    { NODE_PROD, 0, 0, 2, 90, 0 },
    { NODE_PROD, 0, 0, 2, 92, 0 },
    { NODE_SUM, 0, 0, 2, 94, 30 },
    { NODE_PROD, 0, 0, 2, 96, 0 },
    { NODE_PROD, 0, 0, 2, 98, 0 },
    { NODE_SUM, 0, 0, 2, 100, 32 },
    { NODE_PROD, 0, 0, 2, 102, 0 },
    { NODE_PROD, 0, 0, 2, 104, 0 },
    { NODE_SUM, 0, 0, 2, 106, 34 }
};

static const uint16_t g_circuit_children[CHILDREN_ARRAY_SIZE] = {
    22, 24, 25, 22, 24, 23, 24, 27, 28, 20, 26, 21, 29, 30, 31, 20, 29, 21, 29, 33, 34, 18, 32, 19, 35, 36, 37, 16, 38, 39, 16, 38, 17, 38, 41, 42, 14, 40, 15, 43, 44, 45, 14, 43, 15, 43, 47, 48, 12, 46, 13, 49, 50, 51, 10, 52, 53, 10, 52, 11, 52, 55, 56, 8, 54, 9, 57, 58, 59, 8, 57, 9, 57, 61, 62, 6, 60, 7, 63, 64, 65, 4, 66, 67, 4, 66, 5, 66, 69, 70, 2, 68, 3, 71, 72, 73, 2, 71, 3, 71, 75, 76, 0, 74, 1, 77, 78, 79
};

static const Rational g_circuit_weights[WEIGHTS_ARRAY_SIZE] = {
    { 1LL, 500LL },
    { 1LL, 500LL },
    { 499LL, 500LL },
    { 1LL, 4LL },
    { 3LL, 4LL },
    { 1LL, 4LL },
    { 3LL, 4LL },
    { 1LL, 50LL },
    { 49LL, 50LL },
    { 1LL, 50LL },
    { 1LL, 50LL },
    { 49LL, 50LL },
    { 1LL, 3LL },
    { 2LL, 3LL },
    { 1LL, 3LL },
    { 2LL, 3LL },
    { 1LL, 5LL },
    { 4LL, 5LL },
    { 1LL, 100LL },
    { 1LL, 100LL },
    { 99LL, 100LL },
    { 1LL, 10LL },
    { 9LL, 10LL },
    { 1LL, 10LL },
    { 9LL, 10LL },
    { 1LL, 20LL },
    { 19LL, 20LL },
    { 1LL, 2LL },
    { 1LL, 2LL },
    { 1LL, 2LL },
    { 19LL, 20LL },
    { 1LL, 20LL },
    { 19LL, 20LL },
    { 1LL, 20LL },
    { 99LL, 100LL },
    { 1LL, 100LL }
};

#endif /* HIRAM_CIRCUIT_DATA_H */
