/* AUTO-GENERATED BY hiram_c_exporter.py - DO NOT EDIT DIRECTLY */
/* STRICT TOPOLOGICAL DAG LAYOUT FOR MISRA-C:2012 COMPLIANCE */
#ifndef HIRAM_CIRCUIT_DATA_H
#define HIRAM_CIRCUIT_DATA_H

#include "hiram_eval.h"

/* Telemetry Variable IDs */
#define VAR_TERRAIN_CLEAR 0
#define VAR_ALTITUDE_STABLE 1
#define VAR_AUTHORIZE_DESCENT 2
#define VAR_LOW_AIRSPEED 3
#define VAR_HIGH_ANGLE_OF_ATTACK 4
#define VAR_STALL_HAZARD 5
#define VAR_SUBZERO_TEMP 6
#define VAR_HIGH_HUMIDITY 7
#define VAR_ICING_HAZARD 8
#define VAR_HIGH_MACH 9
#define VAR_FLAPS_EXTENDED 10
#define VAR_STRUCTURAL_HAZARD 11
#define NUM_VARIABLES 12
#define HAZARD_VAR_ID 5

#define CIRCUIT_NODE_COUNT 83
#define CIRCUIT_ROOT_ID 82
#define CHILDREN_ARRAY_SIZE 108
#define WEIGHTS_ARRAY_SIZE 36

static const uint16_t g_circuit_children[CHILDREN_ARRAY_SIZE] = {
    11, 12, 13, 10, 14, 11, 17, 19, 20, 18, 21, 16, 22, 15, 23, 9, 24, 10, 22, 16, 22, 27, 28, 26, 29, 25, 30, 8, 31, 32, 7, 33, 8, 31, 37, 31, 36, 38, 35, 39, 34, 40, 6, 41, 7, 39, 35, 39, 44, 45, 43, 46, 42, 47, 5, 48, 49, 4, 50, 5, 48, 54, 48, 53, 55, 52, 56, 51, 57, 3, 58, 4, 56, 52, 56, 61, 62, 60, 63, 59, 64, 2, 65, 66, 1, 67, 2, 65, 71, 65, 70, 72, 69, 73, 68, 74, 0, 75, 1, 73, 69, 73, 78, 79, 77, 80, 76, 81
};

static const Rational g_circuit_weights[WEIGHTS_ARRAY_SIZE] = {
    { 1LL, 500LL },
    { 1LL, 500LL },
    { 499LL, 500LL },
    { 1LL, 4LL },
    { 3LL, 4LL },
    { 1LL, 4LL },
    { 3LL, 4LL },
    { 1LL, 50LL },
    { 49LL, 50LL },
    { 1LL, 50LL },
    { 1LL, 50LL },
    { 49LL, 50LL },
    { 1LL, 3LL },
    { 2LL, 3LL },
    { 1LL, 3LL },
    { 2LL, 3LL },
    { 1LL, 5LL },
    { 4LL, 5LL },
    { 1LL, 100LL },
    { 1LL, 100LL },
    { 99LL, 100LL },
    { 1LL, 10LL },
    { 9LL, 10LL },
    { 1LL, 10LL },
    { 9LL, 10LL },
    { 1LL, 20LL },
    { 19LL, 20LL },
    { 1LL, 2LL },
    { 1LL, 2LL },
    { 1LL, 2LL },
    { 19LL, 20LL },
    { 1LL, 20LL },
    { 19LL, 20LL },
    { 1LL, 20LL },
    { 99LL, 100LL },
    { 1LL, 100LL }
};

static const CircuitNode g_circuit_nodes[CIRCUIT_NODE_COUNT] = {
    { NODE_LITERAL, 0, 0, 0, 0, 0 },
    { NODE_LITERAL, 1, 0, 0, 0, 0 },
    { NODE_LITERAL, 2, 0, 0, 0, 0 },
    { NODE_LITERAL, 3, 0, 0, 0, 0 },
    { NODE_LITERAL, 4, 0, 0, 0, 0 },
    { NODE_LITERAL, 5, 0, 0, 0, 0 },
    { NODE_LITERAL, 6, 0, 0, 0, 0 },
    { NODE_LITERAL, 7, 0, 0, 0, 0 },
    { NODE_LITERAL, 8, 0, 0, 0, 0 },
    { NODE_LITERAL, 9, 0, 0, 0, 0 },
    { NODE_LITERAL, 10, 0, 0, 0, 0 },
    { NODE_LITERAL, 11, 0, 0, 0, 0 },
    { NODE_PROD, 0, 0, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 0, 0 },
    { NODE_SUM, 0, 0, 1, 2, 0 },
    { NODE_PROD, 0, 0, 2, 3, 0 },
    { NODE_LITERAL, 10, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 0, 5, 0 },
    { NODE_PROD, 0, 0, 2, 5, 0 },
    { NODE_LITERAL, 11, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 0, 7, 0 },
    { NODE_PROD, 0, 0, 2, 7, 0 },
    { NODE_SUM, 0, 0, 2, 9, 1 },
    { NODE_PROD, 0, 0, 2, 11, 0 },
    { NODE_SUM, 0, 0, 2, 13, 3 },
    { NODE_PROD, 0, 0, 2, 15, 0 },
    { NODE_LITERAL, 9, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 17, 0 },
    { NODE_PROD, 0, 0, 2, 19, 0 },
    { NODE_SUM, 0, 0, 2, 21, 5 },
    { NODE_PROD, 0, 0, 2, 23, 0 },
    { NODE_SUM, 0, 0, 2, 25, 7 },
    { NODE_PROD, 0, 0, 2, 27, 0 },
    { NODE_SUM, 0, 0, 1, 29, 9 },
    { NODE_PROD, 0, 0, 2, 30, 0 },
    { NODE_LITERAL, 7, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 32, 0 },
    { NODE_LITERAL, 8, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 34, 0 },
    { NODE_SUM, 0, 0, 2, 36, 10 },
    { NODE_PROD, 0, 0, 2, 38, 0 },
    { NODE_SUM, 0, 0, 2, 40, 12 },
    { NODE_PROD, 0, 0, 2, 42, 0 },
    { NODE_LITERAL, 6, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 44, 0 },
    { NODE_PROD, 0, 0, 2, 46, 0 },
    { NODE_SUM, 0, 0, 2, 48, 14 },
    { NODE_PROD, 0, 0, 2, 50, 0 },
    { NODE_SUM, 0, 0, 2, 52, 16 },
    { NODE_PROD, 0, 0, 2, 54, 0 },
    { NODE_SUM, 0, 0, 1, 56, 18 },
    { NODE_PROD, 0, 0, 2, 57, 0 },
    { NODE_LITERAL, 4, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 59, 0 },
    { NODE_LITERAL, 5, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 61, 0 },
    { NODE_SUM, 0, 0, 2, 63, 19 },
    { NODE_PROD, 0, 0, 2, 65, 0 },
    { NODE_SUM, 0, 0, 2, 67, 21 },
    { NODE_PROD, 0, 0, 2, 69, 0 },
    { NODE_LITERAL, 3, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 71, 0 },
    { NODE_PROD, 0, 0, 2, 73, 0 },
    { NODE_SUM, 0, 0, 2, 75, 23 },
    { NODE_PROD, 0, 0, 2, 77, 0 },
    { NODE_SUM, 0, 0, 2, 79, 25 },
    { NODE_PROD, 0, 0, 2, 81, 0 },
    { NODE_SUM, 0, 0, 1, 83, 27 },
    { NODE_PROD, 0, 0, 2, 84, 0 },
    { NODE_LITERAL, 1, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 86, 0 },
    { NODE_LITERAL, 2, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 88, 0 },
    { NODE_SUM, 0, 0, 2, 90, 28 },
    { NODE_PROD, 0, 0, 2, 92, 0 },
    { NODE_SUM, 0, 0, 2, 94, 30 },
    { NODE_PROD, 0, 0, 2, 96, 0 },
    { NODE_LITERAL, 0, 1, 0, 0, 0 },
    { NODE_PROD, 0, 0, 2, 98, 0 },
    { NODE_PROD, 0, 0, 2, 100, 0 },
    { NODE_SUM, 0, 0, 2, 102, 32 },
    { NODE_PROD, 0, 0, 2, 104, 0 },
    { NODE_SUM, 0, 0, 2, 106, 34 }
};

#endif /* HIRAM_CIRCUIT_DATA_H */
