/* AUTO-GENERATED by tools/cpt_exporter.py -- DO NOT EDIT BY HAND. */
/* Source model: data/models/causal_dag.json */
/* Target: ARM Cortex-M7 DTCM, flat static memory, zero heap allocation. */
/*
 * Every array below is emitted from the model's own float.hex() strings,
 * which are byte-for-byte valid C99 hexadecimal-floating-constants -- so
 * each `double` here is the exact same IEEE-754 bit pattern as the Python
 * reference engine (tools/inference_engine.py) uses, with no decimal
 * formatting/rounding step in between.
 */
#ifndef HIRAM_TABLES_H
#define HIRAM_TABLES_H

#define HIRAM_FROZEN_IR_DIGEST "b39845824f903e9230c75110ffd822ccea36cd89a5ebb4eae1235ff4860b57e7"

/* ---- Cardinalities ---- */
#define HIRAM_N_TRACK 3
#define HIRAM_N_OBSTACLE 2
#define HIRAM_N_DECEL 3
#define HIRAM_N_POSTERIOR 6 /* HIRAM_N_OBSTACLE * HIRAM_N_DECEL, index = o * HIRAM_N_DECEL + d */
#define HIRAM_N_SENSOR_STATES 3 /* shared by LidarObs, TofObs, WheelSlipObs */
#define HIRAM_N_ACTIONS 3

/* ---- Actions (order matches the sealed model's loss_matrix.actions) ---- */
#define HIRAM_ACTION_ACCEL 0
#define HIRAM_ACTION_COAST 1
#define HIRAM_ACTION_EMERGENCY_BRAKE 2
#define HIRAM_EMERGENCY_BRAKE_INDEX 2
static const char * const HIRAM_ACTION_NAMES[HIRAM_N_ACTIONS] = {
    "ACCEL", "COAST", "EMERGENCY_BRAKE",
};
/* Lower rank = preferred when two actions tie on expected loss (EMERGENCY_BRAKE > COAST > ACCEL). */
static const int HIRAM_TIE_BREAK_PRIORITY[HIRAM_N_ACTIONS] = { 2, 1, 0 };

/* ---- Parent strides (flat CPT index = parent_state * stride + own_state) ---- */
#define HIRAM_STRIDE_TRACK_TO_OBSTACLE 2
#define HIRAM_STRIDE_TRACK_TO_DECEL 3
#define HIRAM_STRIDE_OBSTACLE_TO_LIDAR 3
#define HIRAM_STRIDE_OBSTACLE_TO_TOF 3
#define HIRAM_STRIDE_DECEL_TO_WHEEL 3

/* ---- Dropout state index (all three sensors share the tri-state DROPOUT=2 convention) ---- */
#define HIRAM_LIDAROBS_DROPOUT_INDEX 2
#define HIRAM_TOFOBS_DROPOUT_INDEX 2
#define HIRAM_WHEELSLIPOBS_DROPOUT_INDEX 2

/* ---- Node CPTs (row-major: parent state(s) outer, own state inner) ---- */
static const double HIRAM_CPT_TRACKCONDITION[3] = {
    0x1.6666666666666p-1, 0x1.999999999999ap-3, 0x1.999999999999ap-4,
};

static const double HIRAM_CPT_TRUEOBSTACLE[6] = {
    0x1.e666666666666p-1, 0x1.999999999999ap-5, 0x1.ccccccccccccdp-1, 0x1.999999999999ap-4,
    0x1.b333333333333p-1, 0x1.3333333333333p-3,
};

static const double HIRAM_CPT_DECELCAPABILITY[9] = {
    0x1.d70a3d70a3d71p-1, 0x1.1eb851eb851ecp-4, 0x1.47ae147ae147bp-7, 0x1.999999999999ap-3,
    0x1.6666666666666p-1, 0x1.999999999999ap-4, 0x1.999999999999ap-5, 0x1.6666666666666p-2,
    0x1.3333333333333p-1,
};

static const double HIRAM_CPT_LIDAROBS[6] = {
    0x1.f5c28f5c28f5cp-1, 0x1.47ae147ae147bp-7, 0x1.47ae147ae147bp-7, 0x1.47ae147ae147bp-6,
    0x1.e666666666666p-1, 0x1.eb851eb851eb8p-6,
};

static const double HIRAM_CPT_TOFOBS[6] = {
    0x1.eb851eb851eb8p-1, 0x1.47ae147ae147bp-6, 0x1.47ae147ae147bp-6, 0x1.47ae147ae147bp-5,
    0x1.d70a3d70a3d71p-1, 0x1.47ae147ae147bp-5,
};

static const double HIRAM_CPT_WHEELSLIPOBS[9] = {
    0x1.e666666666666p-1, 0x1.47ae147ae147bp-5, 0x1.47ae147ae147bp-7, 0x1.3333333333333p-2,
    0x1.5c28f5c28f5c3p-1, 0x1.47ae147ae147bp-6, 0x1.999999999999ap-5, 0x1.ccccccccccccdp-1,
    0x1.999999999999ap-5,
};

/* ---- Loss matrix: flat[action * HIRAM_LOSS_ACTION_STRIDE + o * HIRAM_LOSS_STRIDE_OBSTACLE + d * HIRAM_LOSS_STRIDE_DECEL] ---- */
#define HIRAM_LOSS_ACTION_STRIDE 6
#define HIRAM_LOSS_STRIDE_OBSTACLE 3
#define HIRAM_LOSS_STRIDE_DECEL 1
static const double HIRAM_LOSS_MATRIX[18] = {
    0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.f400000000000p+8, 0x1.f400000000000p+9, 0x1.f400000000000p+10,
    0x1.0000000000000p+1, 0x1.0000000000000p+1, 0x1.0000000000000p+1, 0x1.9000000000000p+6, 0x1.2c00000000000p+8, 0x1.9000000000000p+9,
    0x1.9000000000000p+4, 0x1.9000000000000p+4, 0x1.9000000000000p+4, 0x1.4000000000000p+2, 0x1.4000000000000p+4, 0x1.9000000000000p+5,
};

/* ---- True physical prior P(TrueObstacle, DecelCapability), no evidence ---- */
/* Used as the zero-likelihood fallback distribution; read directly off the
 * already digest-verified Python reference engine at export time, rather
 * than re-derived by this script, so it can never drift out of step. */
static const double HIRAM_PRIOR_MARGINAL[6] = {
    0x1.4dd97f62b6ae8p-1, 0x1.9e4f765fd8adbp-3, 0x1.35dcc63f14121p-4, 0x1.2eb1c432ca57bp-5,
    0x1.63886594af4f2p-6, 0x1.73eab367a0f90p-7,
};

#endif /* HIRAM_TABLES_H */
