/*
 * HIRAM Safety Kernel - Task 3.1: Flat-Memory C Kernel
 * Target: ARM Cortex-M7 DTCM (< 64 KB), zero heap allocation.
 *
 * Ports tools/inference_engine.py's BayesianInferenceEngine.step() (Task
 * 2.2) to flat static arithmetic over the tables generated by
 * tools/cpt_exporter.py into hiram_tables.h: direct marginalization over
 * TrackCondition, tri-state sensor evidence (dropout === unobserved),
 * zero-likelihood fallback to the model's true prior with a forced
 * EMERGENCY_BRAKE, and safety-priority tie-broken expected-loss
 * minimization. See src/hiram_kernel.c for the algorithm; this header only
 * declares the public contract.
 *
 * Zero dynamic memory: this kernel must never call malloc/free/calloc/
 * realloc/alloca. All working memory is the caller-owned, statically-sized
 * hiram_workspace_t below -- there is no heap and no VLA anywhere in the
 * implementation.
 */
#ifndef HIRAM_KERNEL_H
#define HIRAM_KERNEL_H

#include <stdbool.h>
#include <stdint.h>

#include "hiram_tables.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Tri-state sensor evidence contract (mirrors tools/inference_engine.py's
 * EvidenceValue = Optional[int]):
 *   0, 1            -- an observed state, conditioned on normally.
 *   2 (DROPOUT)      -- the sensor's own DROPOUT state index.
 *   HIRAM_UNOBSERVED -- "not observed this step" (Python's None).
 * DROPOUT and HIRAM_UNOBSERVED are semantically identical under this
 * kernel's contract (both marginalize the sensor out analytically, factor
 * 1.0) -- see hiram_kernel_step()'s evidence-canonicalization step. Any
 * other value is rejected as HIRAM_ERR_INVALID_EVIDENCE.
 */
#define HIRAM_UNOBSERVED (-1)

/*
 * This cart model's sealed baseline digest, hardcoded here independently of
 * hiram_tables.h's generated HIRAM_FROZEN_IR_DIGEST (which is only as
 * trustworthy as whatever model tools/cpt_exporter.py was last pointed at).
 * Must equal tools/inference_engine.py's BayesianInferenceEngine.
 * EXPECTED_IR_DIGEST -- hiram_kernel_verify_custody() compares the two
 * digest strings and fails custody if they ever diverge.
 */
#define HIRAM_KERNEL_EXPECTED_IR_DIGEST "b39845824f903e9230c75110ffd822ccea36cd89a5ebb4eae1235ff4860b57e7"

typedef struct {
    int32_t lidar_obs;      /* 0, 1, 2 (DROPOUT), or HIRAM_UNOBSERVED */
    int32_t tof_obs;        /* 0, 1, 2 (DROPOUT), or HIRAM_UNOBSERVED */
    int32_t wheel_slip_obs; /* 0, 1, 2 (DROPOUT), or HIRAM_UNOBSERVED */
} hiram_evidence_t;

typedef enum {
    HIRAM_OK = 0,
    HIRAM_ERR_CUSTODY_MISMATCH = 1, /* embedded HIRAM_FROZEN_IR_DIGEST != the certified baseline */
    HIRAM_ERR_INVALID_EVIDENCE = 2, /* an evidence field outside {-1, 0, .., HIRAM_N_SENSOR_STATES-1} */
    HIRAM_ERR_NULL_POINTER = 3,
} hiram_status_t;

/* Alias onto the generated table macro so this header's struct definition
 * can be stated in terms of a stable, kernel-facing name rather than
 * hiram_tables.h's export-pipeline-internal one -- both always refer to
 * the same single source of truth (HIRAM_N_OBSTACLE * HIRAM_N_DECEL = 6). */
#define HIRAM_POSTERIOR_STATES HIRAM_N_POSTERIOR

/*
 * Caller-owned scratch memory for hiram_kernel_step(). Kept as an explicit
 * struct (rather than function-local arrays) so a caller can place it in a
 * specific memory region via linker/section attributes, and so the kernel
 * itself never needs a stack VLA. The actual implemented footprint is a
 * single 6-double scratchpad (48 bytes) -- see the compile-time size
 * assertions below, which pin down both that exact figure (so any
 * accidental growth is caught immediately) and the < 40 KB Cortex-M7 DTCM
 * ceiling this task targets.
 */
typedef struct {
    double posterior_scratch[HIRAM_POSTERIOR_STATES];
} hiram_workspace_t;

/* Compile-time enforcement (C99: no _Static_assert, so use the classic
 * negative-array-size trick) -- both the exact reconciled footprint (6
 * doubles = 48 bytes) and the hard upper bound this task targets. */
typedef char hiram_workspace_is_48_bytes[(sizeof(hiram_workspace_t) == 48) ? 1 : -1];
typedef char hiram_workspace_fits_budget[(sizeof(hiram_workspace_t) <= 40960) ? 1 : -1];

typedef struct {
    double posterior[HIRAM_N_POSTERIOR];       /* P(TrueObstacle=o, DecelCapability=d | evidence), index o * HIRAM_N_DECEL + d */
    double expected_losses[HIRAM_N_ACTIONS];   /* index matches HIRAM_ACTION_* / HIRAM_ACTION_NAMES */
    int32_t selected_action;                  /* one of HIRAM_ACTION_ACCEL / HIRAM_ACTION_COAST / HIRAM_ACTION_EMERGENCY_BRAKE */
    int32_t selected_action_index;            /* always equal to selected_action; kept as a distinct field per the kernel's explicit output contract */
    bool fallback_active;                      /* true iff the zero-likelihood prior fallback OR an invalid-evidence safety fallback fired (action is always EMERGENCY_BRAKE in that case) */
    hiram_status_t status;                     /* the hiram_status_t this call returned; always mirrors the function's own return value */
} hiram_decision_t;

/*
 * Verifies that the model baked into hiram_tables.h at export time is the
 * certified cart model this kernel was built against: compares
 * HIRAM_FROZEN_IR_DIGEST (compiled in from the JSON's own "ir_digest"
 * field by tools/cpt_exporter.py) against the same sealed baseline digest
 * tools/inference_engine.py's BayesianInferenceEngine.EXPECTED_IR_DIGEST
 * hardcodes. This is a defense-in-depth check against a hand-edited or
 * regenerated-from-a-different-model header slipping past code review --
 * it cannot detect in-field data corruption of the tables themselves (the
 * arrays are `static const` in flash/ROM on the target, not re-verified by
 * hash at runtime; an on-device SHA-256 over the whole JSON is out of scope
 * for a flat-memory transpilation of the algorithm).
 *
 * Returns HIRAM_OK if the digest matches, HIRAM_ERR_CUSTODY_MISMATCH
 * otherwise. Callers must call this once (e.g. at startup) before trusting
 * hiram_kernel_step()'s output.
 */
hiram_status_t hiram_kernel_verify_custody(void);

/*
 * Runs one inference + decision cycle: computes the posterior over
 * (TrueObstacle, DecelCapability) given `evidence` (marginalizing
 * TrackCondition and any unobserved/DROPOUT sensor), falls back to the
 * model's true prior with a forced EMERGENCY_BRAKE if the evidence is
 * degenerate (joint likelihood below the zero-likelihood guard), evaluates
 * expected loss per action against HIRAM_LOSS_MATRIX, and selects the
 * loss-minimizing action with EMERGENCY_BRAKE > COAST > ACCEL tie-breaking.
 * Writes the result into `*out`; `*ws` is scratch space, contents undefined
 * on return.
 *
 * Returns HIRAM_ERR_NULL_POINTER if any pointer is NULL (evidence/ws/out
 * are all left untouched in that case -- there is no `*out` to write into).
 *
 * Returns HIRAM_ERR_INVALID_EVIDENCE if an evidence field is outside
 * {HIRAM_UNOBSERVED} u [0, HIRAM_N_SENSOR_STATES); *out is still fully
 * populated in this case -- to the same safe EMERGENCY_BRAKE-over-the-prior
 * fallback contract as the zero-likelihood path -- specifically so a
 * caller reusing a `hiram_decision_t` across calls never observes a stale
 * decision (e.g. an earlier call's ACCEL) left over from before the
 * rejected call. `out->status` mirrors the return value on every path.
 *
 * Otherwise returns HIRAM_OK.
 */
hiram_status_t hiram_kernel_step(const hiram_evidence_t *evidence, hiram_workspace_t *ws, hiram_decision_t *out);

#ifdef __cplusplus
}
#endif

#endif /* HIRAM_KERNEL_H */
