"""
tools.cpt_exporter - Flat-memory C header exporter for the HIRAM safety
kernel's cart model (Task 3.1).

Reads the sealed causal DAG IR (the same file tools.inference_engine loads)
and emits include/hiram_tables.h: a self-contained, auto-generated C header
of `static const double` CPT/loss-matrix arrays, parent strides, and a few
derived constants (prior marginal, safety tie-break priorities, emergency
brake index) that Phase 3's flat-memory C kernel (src/hiram_kernel.c) reads
by index -- no parsing, no allocation, no recursion at runtime.

Bit-exactness: every double is emitted using the model's own precomputed
`*_hex` fields (Python float.hex() strings, e.g. "0x1.f5c28f5c28f5cp-1").
That format is byte-for-byte a C99 hexadecimal-floating-constant, so pasting
it verbatim into the header round-trips through the C compiler to the exact
same IEEE-754 bit pattern as the Python double it came from -- no decimal
formatting/rounding step, and no risk of losing precision in translation.

Sealed custody: this script verifies the loaded model's "ir_digest" the same
two ways tools.inference_engine.BayesianInferenceEngine.__init__ does
(internal self-consistency, then baseline match against the frozen digest),
by simply constructing that engine -- which raises ValueError on either
mismatch before this script reads a single field. The derived constants that
require *running* the model (the true prior marginal P(TrueObstacle,
DecelCapability) with no evidence) are read directly off that same engine
instance rather than re-derived here, so there is exactly one place
(inference_engine.py) that implements the marginalization arithmetic --
this script never risks transcribing it a second time out of step.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import List

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from tools.inference_engine import BayesianInferenceEngine  # noqa: E402

FROZEN_IR_DIGEST = BayesianInferenceEngine.EXPECTED_IR_DIGEST
DEFAULT_MODEL_PATH = Path("data/models/causal_dag.json")
OUTPUT_HEADER_PATH = Path("include/hiram_tables.h")

_TRACK_NODE = "TrackCondition"
_OBSTACLE_NODE = "TrueObstacle"
_DECEL_NODE = "DecelCapability"
_SENSOR_NODES = ("LidarObs", "TofObs", "WheelSlipObs")


def _emit_hex_array(lines: List[str], c_type: str, name: str, hex_values: List[str], n_per_line: int = 4) -> None:
    lines.append(f"static const {c_type} {name}[{len(hex_values)}] = {{")
    for i in range(0, len(hex_values), n_per_line):
        row = ", ".join(hex_values[i : i + n_per_line])
        lines.append(f"    {row},")
    lines.append("};")


def generate_c_header(model_path: Path, output_path: Path) -> None:
    # Constructing the engine performs the full two-layer ir_digest custody
    # check (self-consistency + frozen-baseline match) and raises ValueError
    # on any violation -- this script deliberately does not duplicate that
    # check, to avoid the two implementations ever drifting apart.
    engine = BayesianInferenceEngine(model_path=str(model_path))
    model = engine._model  # noqa: SLF001 -- same trusted module, already digest-verified above
    nodes = model["nodes"]
    loss = model["loss_matrix"]

    track_states = len(nodes[_TRACK_NODE]["states"])
    obstacle_states = len(nodes[_OBSTACLE_NODE]["states"])
    decel_states = len(nodes[_DECEL_NODE]["states"])
    n_posterior = obstacle_states * decel_states
    sensor_states = len(nodes[_SENSOR_NODES[0]]["states"])
    for s in _SENSOR_NODES:
        if len(nodes[s]["states"]) != sensor_states:
            raise ValueError(f"expected all sensor nodes to share a state count; '{s}' does not")

    actions: List[str] = loss["actions"]
    n_actions = len(actions)
    action_stride = loss["action_stride"]
    obstacle_loss_stride = loss["dependency_strides"][_OBSTACLE_NODE]
    decel_loss_stride = loss["dependency_strides"][_DECEL_NODE]

    tie_break_priority = {"EMERGENCY_BRAKE": 0, "COAST": 1, "ACCEL": 2}
    if any(a not in tie_break_priority for a in actions):
        raise ValueError(f"loss matrix actions {actions!r} contain an action this exporter has no tie-break rank for")
    priority_by_index = [tie_break_priority[a] for a in actions]
    emergency_brake_index = actions.index("EMERGENCY_BRAKE")

    prior_marginal_hex = [v.hex() for v in engine._prior_marginal]  # noqa: SLF001

    lines: List[str] = []
    lines.append("/* AUTO-GENERATED by tools/cpt_exporter.py -- DO NOT EDIT BY HAND. */")
    lines.append(f"/* Source model: {model_path.as_posix()} */")
    lines.append("/* Target: ARM Cortex-M7 DTCM, flat static memory, zero heap allocation. */")
    lines.append("/*")
    lines.append(" * Every array below is emitted from the model's own float.hex() strings,")
    lines.append(" * which are byte-for-byte valid C99 hexadecimal-floating-constants -- so")
    lines.append(" * each `double` here is the exact same IEEE-754 bit pattern as the Python")
    lines.append(" * reference engine (tools/inference_engine.py) uses, with no decimal")
    lines.append(" * formatting/rounding step in between.")
    lines.append(" */")
    lines.append("#ifndef HIRAM_TABLES_H")
    lines.append("#define HIRAM_TABLES_H")
    lines.append("")
    lines.append(f'#define HIRAM_FROZEN_IR_DIGEST "{model["ir_digest"]}"')
    lines.append("")

    lines.append("/* ---- Cardinalities ---- */")
    lines.append(f"#define HIRAM_N_TRACK {track_states}")
    lines.append(f"#define HIRAM_N_OBSTACLE {obstacle_states}")
    lines.append(f"#define HIRAM_N_DECEL {decel_states}")
    lines.append(f"#define HIRAM_N_POSTERIOR {n_posterior} /* HIRAM_N_OBSTACLE * HIRAM_N_DECEL, index = o * HIRAM_N_DECEL + d */")
    lines.append(f"#define HIRAM_N_SENSOR_STATES {sensor_states} /* shared by LidarObs, TofObs, WheelSlipObs */")
    lines.append(f"#define HIRAM_N_ACTIONS {n_actions}")
    lines.append("")

    lines.append("/* ---- Actions (order matches the sealed model's loss_matrix.actions) ---- */")
    for idx, action in enumerate(actions):
        lines.append(f"#define HIRAM_ACTION_{action} {idx}")
    lines.append(f"#define HIRAM_EMERGENCY_BRAKE_INDEX {emergency_brake_index}")
    lines.append("static const char * const HIRAM_ACTION_NAMES[HIRAM_N_ACTIONS] = {")
    lines.append("    " + ", ".join(f'"{a}"' for a in actions) + ",")
    lines.append("};")
    lines.append("/* Lower rank = preferred when two actions tie on expected loss (EMERGENCY_BRAKE > COAST > ACCEL). */")
    lines.append(f"static const int HIRAM_TIE_BREAK_PRIORITY[HIRAM_N_ACTIONS] = {{ {', '.join(str(p) for p in priority_by_index)} }};")
    lines.append("")

    lines.append("/* ---- Parent strides (flat CPT index = parent_state * stride + own_state) ---- */")
    lines.append(f'#define HIRAM_STRIDE_TRACK_TO_OBSTACLE {nodes[_OBSTACLE_NODE]["parent_strides"][_TRACK_NODE]}')
    lines.append(f'#define HIRAM_STRIDE_TRACK_TO_DECEL {nodes[_DECEL_NODE]["parent_strides"][_TRACK_NODE]}')
    lines.append(f'#define HIRAM_STRIDE_OBSTACLE_TO_LIDAR {nodes["LidarObs"]["parent_strides"][_OBSTACLE_NODE]}')
    lines.append(f'#define HIRAM_STRIDE_OBSTACLE_TO_TOF {nodes["TofObs"]["parent_strides"][_OBSTACLE_NODE]}')
    lines.append(f'#define HIRAM_STRIDE_DECEL_TO_WHEEL {nodes["WheelSlipObs"]["parent_strides"][_DECEL_NODE]}')
    lines.append("")

    lines.append("/* ---- Dropout state index (all three sensors share the tri-state DROPOUT=2 convention) ---- */")
    for s in _SENSOR_NODES:
        idx = nodes[s]["dropout_state_index"]
        if idx is None:
            raise ValueError(f"sensor node '{s}' has no dropout_state_index; this exporter assumes all sensors declare one")
        lines.append(f"#define HIRAM_{s.upper()}_DROPOUT_INDEX {idx}")
    lines.append("")

    lines.append("/* ---- Node CPTs (row-major: parent state(s) outer, own state inner) ---- */")
    _emit_hex_array(lines, "double", "HIRAM_CPT_TRACKCONDITION", nodes[_TRACK_NODE]["cpt_hex"])
    lines.append("")
    _emit_hex_array(lines, "double", "HIRAM_CPT_TRUEOBSTACLE", nodes[_OBSTACLE_NODE]["cpt_hex"])
    lines.append("")
    _emit_hex_array(lines, "double", "HIRAM_CPT_DECELCAPABILITY", nodes[_DECEL_NODE]["cpt_hex"])
    lines.append("")
    _emit_hex_array(lines, "double", "HIRAM_CPT_LIDAROBS", nodes["LidarObs"]["cpt_hex"])
    lines.append("")
    _emit_hex_array(lines, "double", "HIRAM_CPT_TOFOBS", nodes["TofObs"]["cpt_hex"])
    lines.append("")
    _emit_hex_array(lines, "double", "HIRAM_CPT_WHEELSLIPOBS", nodes["WheelSlipObs"]["cpt_hex"])
    lines.append("")

    lines.append("/* ---- Loss matrix: flat[action * HIRAM_LOSS_ACTION_STRIDE + o * HIRAM_LOSS_STRIDE_OBSTACLE + d * HIRAM_LOSS_STRIDE_DECEL] ---- */")
    lines.append(f"#define HIRAM_LOSS_ACTION_STRIDE {action_stride}")
    lines.append(f"#define HIRAM_LOSS_STRIDE_OBSTACLE {obstacle_loss_stride}")
    lines.append(f"#define HIRAM_LOSS_STRIDE_DECEL {decel_loss_stride}")
    _emit_hex_array(lines, "double", "HIRAM_LOSS_MATRIX", loss["matrix_hex"], n_per_line=action_stride)
    lines.append("")

    lines.append("/* ---- True physical prior P(TrueObstacle, DecelCapability), no evidence ---- */")
    lines.append("/* Used as the zero-likelihood fallback distribution; read directly off the")
    lines.append(" * already digest-verified Python reference engine at export time, rather")
    lines.append(" * than re-derived by this script, so it can never drift out of step. */")
    _emit_hex_array(lines, "double", "HIRAM_PRIOR_MARGINAL", prior_marginal_hex)
    lines.append("")

    lines.append("#endif /* HIRAM_TABLES_H */")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {output_path} from {model_path} (ir_digest={model['ir_digest']}).")


if __name__ == "__main__":
    model_file = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_MODEL_PATH
    out_file = Path(sys.argv[2]) if len(sys.argv) > 2 else OUTPUT_HEADER_PATH
    generate_c_header(model_file, out_file)
