import sys, pathlib
from fractions import Fraction
from hiram_compiler import compile_from_rules, Rule, CANONICAL_PRIORS, CANONICAL_RULES, FLIGHT_VAR_NAMES
from hiram_ac import NODE_LITERAL, NODE_PROD, NODE_SUM

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

def export_c_header(kb, output_path):
    circuit, root = kb.circuit, kb.root
    node_count = len(circuit)

    children_array = []
    weights_array = []
    c_nodes = []

    for i in range(node_count):
        n = circuit[i]
        ntype = n['type']
        if ntype == NODE_LITERAL:
            c_nodes.append(f"    {{ NODE_LITERAL, {n['var_id']}, {n['is_negated']}, 0, 0, 0 }}")
        elif ntype == NODE_PROD:
            ch_offset = len(children_array)
            ch_count = len(n['children'])
            children_array.extend(n['children'])
            c_nodes.append(f"    {{ NODE_PROD, 0, 0, {ch_count}, {ch_offset}, 0 }}")
        elif ntype == NODE_SUM:
            ch_offset = len(children_array)
            w_offset = len(weights_array)
            ch_count = len(n['children'])
            children_array.extend(n['children'])
            for w in n['weights']:
                weights_array.append(f"    {{ {w.numerator}LL, {w.denominator}LL }}")
            c_nodes.append(f"    {{ NODE_SUM, 0, 0, {ch_count}, {ch_offset}, {w_offset} }}")

    lines = [
        "/* AUTO-GENERATED BY hiram_c_exporter.py - ZERO-MALLOC EMBEDDED C RUNTIME */",
        "/* MISRA-C:2012 Rule 17.2 Compliant: Static Topological Circuit Tables */",
        "#ifndef HIRAM_CIRCUIT_DATA_H",
        "#define HIRAM_CIRCUIT_DATA_H",
        "",
        "/* Circuit dimensions are defined BEFORE including hiram_eval.h so that",
        "   HiramContext.memo is sized from the authoritative generated value.",
        "   hiram_eval.h carries no default: a translation unit that allocates a",
        "   HiramContext without this header fails to compile rather than silently",
        "   building a context smaller than the kernel writes into. */",
        f"#define CIRCUIT_NODE_COUNT   {node_count}",
        f"#define CIRCUIT_ROOT_ID      {root}",
        f"#define HAZARD_VAR_ID        {kb.var_to_id['stall_hazard']}",
        f"#define CHILDREN_ARRAY_SIZE  {len(children_array)}",
        f"#define WEIGHTS_ARRAY_SIZE   {len(weights_array)}",
        "",
        '#include "hiram_eval.h"',
        "",
        "",
        "",
        "/* Variable ID aliases */"
    ]
    for name, vid in sorted(kb.var_to_id.items(), key=lambda x: x[1]):
        lines.append(f"#define VAR_{name.upper():<24} {vid}")
    lines.append("")

    lines.append("static const CircuitNode g_circuit_nodes[CIRCUIT_NODE_COUNT] = {")
    lines.append(",\n".join(c_nodes))
    lines.append("};\n")

    lines.append("static const uint16_t g_circuit_children[CHILDREN_ARRAY_SIZE] = {")
    lines.append("    " + ", ".join(map(str, children_array)))
    lines.append("};\n")

    lines.append("static const Rational g_circuit_weights[WEIGHTS_ARRAY_SIZE] = {")
    lines.append(",\n".join(weights_array))
    lines.append("};\n")

    lines.append("#endif /* HIRAM_CIRCUIT_DATA_H */\n")

    header_content = "\n".join(lines)
    output_path.write_text(header_content, encoding="utf-8")
    return header_content

def main():
    kb = compile_from_rules(CANONICAL_RULES, CANONICAL_PRIORS)

    out_dir = pathlib.Path.cwd()
    if (out_dir / "include/hiram").exists():
        target_path = out_dir / "include/hiram/hiram_circuit_data.h"
    else:
        target_path = out_dir / "hiram_circuit_data.h"

    export_c_header(kb, target_path)

    # Only hiram_circuit_data.h is generated. hiram_eval.c and hiram_eval.h are
    # hand-written, and this used to copy them beside the generated header so a
    # harness could "verify reproducibility" by diffing a copy against its own
    # source -- a check that could not fail. Reproducibility is now claimed for
    # the one artifact that is actually generated.

if __name__ == "__main__":
    main()